title: Redmineで始める異世界人心掌握術
author: 8amjp
description: >
  チケットを制する者が異世界を制す!?貴方もプロジェクトマネジメント!
  [異世界ファンタジー/長編]
index: manual

type: novel
google_analytics: UA-41627578-3
twitter:
  username: 8amjp

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag