title: Redmineで始める異世界人心掌握術
description: >
  チケットを制する者が異世界を制す!?貴方もプロジェクトマネジメント!
index: manual

author: 8amjp
image: site-icon.png
type: novel
card: summary
google_analytics: UA-41627578-3
twitter:
  username: 8amjp

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag